name: template-build-quarto-docs

on:
  workflow_call:
    inputs:
      checkout-ref:
        description: "checkout ref"
        required: false
        type: string
        default: "refs/heads/master"
      unused-variable:
        description: unused-variable
        required: false
        type: string
        default: dummy    
  
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: Build and assemble main document
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.checkout-ref }}
          fetch-depth: 0

      - uses: astral-sh/setup-uv@v4

      - uses: quarto-dev/quarto-actions/setup@v2.2.0

      - name: Render Quarto site
        uses: quarto-dev/quarto-actions/render@v2.2.0
        with:
          path: docs
          to: html

      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2.2.0
        with:
          path: docs
          target: gh-pages
          render: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  