name: template-publish-uv-pypi

on:
  workflow_call:
    inputs:
      checkout-ref:
        description: "checkout ref"
        required: false
        type: string
        default: "refs/heads/master"
      build-args:
        description: "build-args"
        required: false
        type: string
        default: -v
      publish-args:
        description: "publish-args"
        required: false
        type: string
        default: -vvv
    secrets:
      pypi_api_token:
        required: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.checkout-ref }}

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Build wheel
        run: uv build ${{ inputs.build-args }}

      - name: Publish to PyPI
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.pypi_api_token }}
        run: uv publish ${{ inputs.publish-args }}
